### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Wev0n** [huanngzh/ComfyUI-MVAdapter#28]
I get this when attempting to lower the num_views value on either DiffusersModelMakeup/MVSamplerNode nodes to less than 6. I don't need to generate extra three-quarter nor profile views for my images (im using i2mv sdxl ldm workflow), is it possible to allow for even lower view count?

!!! Exception during processing !!! The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 448, in sample
    control_images = prepare_camera_embed(num_views, width, self.torch_device)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\utils.py", line 298, in prepare_camera_embed
    cameras = get_orthogonal_camera(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\utils\camera.py", line 195, in get_orthogonal_camera
    c2w = get_c2w(elevation_deg, distance, azimuth_deg, num_views, device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\utils\camera.py", line 46, in get_c2w
    camera_distances * torch.cos(elevation) * torch.cos(azimuth),
    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 0

**Comment by planb788** [comment]
I don't know why, but I can only change the perspective to the one with 6 images without getting an error. Changing it to 3 causes this error.

**Comment by Wev0n** [comment]
> I don't know why, but I can only change the perspective to the one with 6 images without getting an error. Changing it to 3 causes this error.

Lower than 6? It the DiffusersModelMakeup node or the MVSamplerNode?

**Comment by botnang** [comment]
> I don't know why, but I can only change the perspective to the one with 6 images without getting an error. Changing it to 3 causes this error.

same here....

**Comment by huanngzh** [comment]
Now the released model only supports the generation of the six views at the fixed positions. So we do not recommend modifying `num_views` parameter.

**Comment by CoraAI** [comment]
> Now the released model only supports the generation of the six views at the fixed positions. So we do not recommend modifying `num_views` parameter.

Any chance down to 4 or lesser? Would have been a lot better  having more details of each view than more views but all too small.

**Comment by Wev0n** [comment]
> > Now the released model only supports the generation of the six views at the fixed positions. So we do not recommend modifying `num_views` parameter.
> 
> Any chance down to 4 or lesser? Would have been a lot better having more details of each view than more views but all too small.

X2 it takes me 7 minutes to generate 6 views at 512x512 on my RTX 4060 laptop when I don't even need 3 of those images

**Comment by huanngzh** [comment]
@Wev0n @planb788 @north151 @botnang @CoraAI Hi, please check our latest update. Now it can support specifying views to generate! Follow [here](https://github.com/huanngzh/ComfyUI-MVAdapter?tab=readme-ov-file#view-selection) to enjoy it!
