### ISSUE TITLE
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.

### ISSUE THREAD

**Issue by xueqing0622** [huanngzh/ComfyUI-MVAdapter#8]
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
 98%|█████████████████████████████████████████████████████████████████████████████▍ | 49/50 [1:11:05<06:35, 395.55s/it]cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.

**Comment by xueqing0622** [comment]
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
cross_attention_kwargs ['mv_scale', 'ref_hidden_states', 'ref_scale'] are not expected by AttnProcessor2_0 and will be ignored.
100%|████████████████████████████████████████████████████████████████████████████████| 50/50 [1:15:32<00:00, 90.65s/it]

**Comment by xueqing0622** [comment]
100%|████████████████████████████████████████████████████████████████████████████████| 50/50 [1:15:32<00:00, 90.65s/it]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "G:\MV-Adapter-oneky-T8\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\MV-Adapter-oneky-T8\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\MV-Adapter-oneky-T8\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\MV-Adapter-oneky-T8\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\MV-Adapter-oneky-T8\ComfyUI\custom_nodes\ComfyUI-MVAdapter\nodes.py", line 410, in sample
    images = pipeline(
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\ComfyUI\custom_nodes\ComfyUI-MVAdapter\mvadapter\pipelines\pipeline_mvadapter_i2mv_sdxl.py", line 853, in __call__
    image = self.vae.decode(latents, return_dict=False)[0]
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 326, in decode
    decoded = self._decode(z).sample
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 297, in _decode
    dec = self.decoder(z)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\models\autoencoders\vae.py", line 337, in forward
    sample = up_block(sample, latent_embeds)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\models\unets\unet_2d_blocks.py", line 2750, in forward
    hidden_states = upsampler(hidden_states)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\diffusers\models\upsampling.py", line 180, in forward
    hidden_states = self.conv(hidden_states)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "G:\MV-Adapter-oneky-T8\Python\lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
    return F.conv2d(
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.

**Comment by xueqing0622** [comment]
3060 12G

**Comment by huanngzh** [comment]
We have added a new option `enable_vae_slicing` to the Diffusers Model Makeup node. We recommend you to re-install our repo and enable the `enable_vae_slicing` to `True`, which will reduce the memory need for vae decoding.

![image](https://github.com/user-attachments/assets/bd494afc-5307-4cf0-9937-d608aaa5d8f4)

Btw, if you are using LDM VAE Loader, please set the `upcast_fp32` to `False`, for lower memory need.

![image](https://github.com/user-attachments/assets/d1363923-686a-4fdb-9d46-53023634529f)

If you still get errors, feel free to let us know and we will fix it further.

**Comment by xueqing0622** [comment]
12G vram OutOfMemoryError: when after run out all step when output image.

**Comment by xueqing0622** [comment]
still same issue,

**Comment by ViniciusFXavier** [comment]
> We have added a new option `enable_vae_slicing` to the Diffusers Model Makeup node. We recommend you to re-install our repo and enable the `enable_vae_slicing` to `True`, which will reduce the memory need for vae decoding.
> 
> ![image](https://private-user-images.githubusercontent.com/78398294/393467268-bd494afc-5307-4cf0-9937-d608aaa5d8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODMwMjQsIm5iZiI6MTczMzY4MjcyNCwicGF0aCI6Ii83ODM5ODI5NC8zOTM0NjcyNjgtYmQ0OTRhZmMtNTMwNy00Y2YwLTk5MzctZDYwOGFhYTVkOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE4MzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTQzNWRiMDQ0NjFlZDEwODNjN2JlMWI5NjY5NThiNDVlY2U3OWI0YjgzZTVmYWE2N2FkZjVjNWI5NzQwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.maRWHqxd0eZUVRP1VX9AQkuvI4ZVABmMxt8AbFb7DiU)
> 
> Btw, if you are using LDM VAE Loader, please set the `upcast_fp32` to `False`, for lower memory need.
> 
> ![image](https://private-user-images.githubusercontent.com/78398294/393467276-d1363923-686a-4fdb-9d46-53023634529f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODMwMjQsIm5iZiI6MTczMzY4MjcyNCwicGF0aCI6Ii83ODM5ODI5NC8zOTM0NjcyNzYtZDEzNjM5MjMtNjg2YS00ZmRiLTlkNDYtNTMwMjM2MzQ1MjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE4MzIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWUzYjhiNmI4NjZhYWIwY2IxZTUwNzRiOWI1NjExNjljNzM1NGM4N2JkNzYzZjI4NDVmODcxZGJjYzhiYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pR9KyX_3GmoeX-NXxNYe0HJXnXZvqY-w-6GaUY2nTx0)
> 
> If you still get errors, feel free to let us know and we will fix it further.

Same issue here.

Using current version: https://github.com/huanngzh/ComfyUI-MVAdapter/tree/1c103af221dad2089bc8eef82cbc70344bfcde5a
Updated 5 hours ago. 

![image](https://github.com/user-attachments/assets/0bd17901-378e-4988-abbb-34189f251fbf)

![image](https://github.com/user-attachments/assets/880450ce-32b1-4d5d-9332-18957f234d44)

**Comment by coddz** [comment]
still same issue.

**Comment by metal3d** [comment]
Same issue with RTX 3090 FE, 24Go RAM. Using I2M pipeline, VAE to fp16, VAE Slicing and base SDXL model. I also tried to start comfyUI with "--novram".

Whatever I do, restarting ComfyUI, Reinstalling the repository, I've got an OOM.

This is not a criticism; I'm very happy to see developers working on this kind of node, which can really help. I'm just giving my unfortunately unsuccessful result.

Hopefully we'll find a way to understand and run this superb node.
